export const PLANT_TYPES = [
  {
    id: "pothos",
    name: "Pothos",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Low to bright indirect",
    tips: [
      "Allow the top inch of soil to dry out between waterings.",
      "Tolerates low light but grows faster in bright indirect light.",
      "Yellowing leaves usually mean overwatering.",
      "Wipe leaves occasionally to remove dust.",
      "Toxic to pets — keep out of reach.",
    ],
  },
  {
    id: "snake_plant",
    name: "Snake Plant",
    emoji: "🌵",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Low to bright indirect",
    tips: [
      "One of the most drought-tolerant houseplants — less water is more.",
      "Overwatering is the #1 killer; let soil dry completely between waterings.",
      "Thrives in almost any light condition.",
      "Repot only when roots are visibly crowded.",
      "Air-purifying: great for bedrooms.",
    ],
  },
  {
    id: "peace_lily",
    name: "Peace Lily",
    emoji: "🌸",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Low to medium indirect",
    tips: [
      "Will dramatically droop when thirsty — a built-in watering reminder!",
      "Prefers distilled or filtered water; sensitive to fluoride.",
      "Wipe leaves to keep them glossy and help with photosynthesis.",
      "Blooms best with some indirect light.",
      "Toxic to pets and children.",
    ],
  },
  {
    id: "spider_plant",
    name: "Spider Plant",
    emoji: "🕷️",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Very forgiving — tolerates irregular watering.",
      "Brown tips can indicate dry air or fluoride in tap water.",
      "The baby 'spiderettes' can be propagated in water.",
      "Great for hanging baskets.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "monstera",
    name: "Monstera",
    emoji: "🌴",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water when the top 1–2 inches of soil feel dry.",
      "Needs a moss pole or support as it grows.",
      "Mist leaves or use a humidifier for best results.",
      "Wipe large leaves with a damp cloth regularly.",
      "Toxic to pets and humans if ingested.",
    ],
  },
  {
    id: "fiddle_leaf_fig",
    name: "Fiddle Leaf Fig",
    emoji: "🌳",
    wateringIntervalDays: 7,
    difficulty: "Hard",
    light: "Bright indirect",
    tips: [
      "Hates being moved — find a good spot and keep it there.",
      "Water consistently; avoid letting it sit in water.",
      "Needs lots of bright indirect light.",
      "Brown spots on edges = underwatering; brown spots in middle = overwatering.",
      "Dust leaves monthly to support photosynthesis.",
    ],
  },
  {
    id: "succulents",
    name: "Succulents",
    emoji: "🌵",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Full sun to bright indirect",
    tips: [
      "Use well-draining cactus/succulent mix.",
      "Water deeply but infrequently — soak and dry method.",
      "Reduce watering to once a month in winter.",
      "Need at least 6 hours of light per day.",
      "Leggy growth means they need more light.",
    ],
  },
  {
    id: "zz_plant",
    name: "ZZ Plant",
    emoji: "🌱",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Low to bright indirect",
    tips: [
      "Extremely drought tolerant — stores water in its roots.",
      "Allow soil to dry completely between waterings.",
      "Tolerates low light better than almost any other plant.",
      "Slow grower but very long-lived.",
      "Toxic if ingested — wash hands after handling.",
    ],
  },
  {
    id: "aloe_vera",
    name: "Aloe Vera",
    emoji: "🌿",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect to direct",
    tips: [
      "Water deeply then let soil dry completely — every 2–3 weeks.",
      "Plant in well-draining soil or cactus mix.",
      "The gel in leaves is great for minor burns and skin irritation.",
      "Brown tips may indicate too much fluoride in water.",
      "Bring inside if temperatures drop below 50°F.",
    ],
  },
  {
    id: "orchid",
    name: "Orchid",
    emoji: "🌺",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water by placing in a sink for 15 minutes, then drain fully.",
      "Never let roots sit in standing water.",
      "Use orchid-specific potting mix (bark-based).",
      "Fertilize with diluted orchid fertilizer monthly.",
      "After blooming, cut spike above a node to encourage re-blooming.",
    ],
  },
  {
    id: "rubber_plant",
    name: "Rubber Plant",
    emoji: "🌳",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Wipe leaves with a damp cloth to keep them shiny.",
      "Avoid cold drafts and sudden temperature changes.",
      "Prune to encourage bushier growth.",
      "Toxic to pets and humans.",
    ],
  },
  {
    id: "basil",
    name: "Basil",
    emoji: "🌿",
    wateringIntervalDays: 2,
    difficulty: "Moderate",
    light: "Full sun",
    tips: [
      "Keep soil consistently moist but not waterlogged.",
      "Water at the base to avoid fungal issues.",
      "Pinch flower buds to keep leaves producing.",
      "Needs 6–8 hours of direct sunlight per day.",
      "Harvest frequently to encourage bushy growth.",
    ],
  },
  {
    id: "lavender",
    name: "Lavender",
    emoji: "💜",
    wateringIntervalDays: 10,
    difficulty: "Moderate",
    light: "Full sun",
    tips: [
      "Thrives in dry, well-drained soil — avoid overwatering.",
      "Needs full sun (6+ hours/day).",
      "Prune after flowering to maintain shape.",
      "Great natural insect repellent.",
      "Drought-tolerant once established.",
    ],
  },
  {
    id: "boston_fern",
    name: "Boston Fern",
    emoji: "🌿",
    wateringIntervalDays: 3,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Keep soil consistently moist — never let it dry out completely.",
      "Loves humidity; mist daily or use a pebble tray with water.",
      "Fronds yellow if it's too dry or too cold.",
      "Great air purifier.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "cactus",
    name: "Cactus",
    emoji: "🌵",
    wateringIntervalDays: 21,
    difficulty: "Easy",
    light: "Full sun to bright indirect",
    tips: [
      "Water sparingly — once every 2–3 weeks in summer, once a month in winter.",
      "Use fast-draining cactus soil.",
      "Handle with care using tongs or thick gloves.",
      "Need bright light — a south-facing windowsill is ideal.",
      "Don't mist; they prefer dry air.",
    ],
  },
  {
    id: "calathea",
    name: "Calathea",
    emoji: "🌿",
    wateringIntervalDays: 5,
    difficulty: "Hard",
    light: "Low to medium indirect",
    tips: [
      "Use filtered or rainwater — sensitive to fluoride and chlorine.",
      "Keep soil consistently moist but never soggy.",
      "Needs high humidity (60%+); use a humidifier or pebble tray.",
      "Leaves curl inward when underwatered or too cold.",
      "Avoid direct sunlight — it bleaches the beautiful leaf patterns.",
    ],
  },
  {
    id: "philodendron",
    name: "Philodendron",
    emoji: "🌱",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Low to bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Trailing types look great in hanging baskets; climbing types need a pole.",
      "Yellow leaves usually mean overwatering.",
      "Wipe leaves to keep them glossy.",
      "Toxic to pets and humans if ingested.",
    ],
  },
  {
    id: "dracaena",
    name: "Dracaena",
    emoji: "🌴",
    wateringIntervalDays: 10,
    difficulty: "Easy",
    light: "Low to bright indirect",
    tips: [
      "Water when the top half of soil is dry.",
      "Sensitive to fluoride — use filtered water if possible.",
      "Brown leaf tips usually indicate dry air or fluoride buildup.",
      "Thrives in a wide range of light conditions.",
      "Toxic to pets — keep out of reach.",
    ],
  },
  {
    id: "tradescantia",
    name: "Tradescantia",
    emoji: "💜",
    wateringIntervalDays: 5,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil feels dry.",
      "Pinch back leggy stems to encourage bushier growth.",
      "More light = more vivid purple coloring.",
      "Propagates extremely easily — just cut and root in water.",
      "Mild skin irritant for some people; toxic if ingested by pets.",
    ],
  },
  {
    id: "pilea",
    name: "Pilea (Chinese Money Plant)",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Rotate the pot weekly for even, symmetrical growth.",
      "Produces lots of offshoots ('pups') that can be separated and potted.",
      "Prefers well-draining soil; don't let it sit in water.",
      "Drooping leaves mean it needs water; yellowing means too much.",
    ],
  },
  {
    id: "cast_iron_plant",
    name: "Cast Iron Plant",
    emoji: "🌿",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Low to medium indirect",
    tips: [
      "One of the toughest houseplants — tolerates neglect, low light, and temperature swings.",
      "Water sparingly; allow soil to dry between waterings.",
      "Grows slowly but lives for decades.",
      "Avoid direct sun which will scorch the dark leaves.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "prayer_plant",
    name: "Prayer Plant",
    emoji: "🌿",
    wateringIntervalDays: 5,
    difficulty: "Moderate",
    light: "Medium indirect",
    tips: [
      "Named for its leaves that fold up at night like praying hands.",
      "Keep soil consistently moist but not waterlogged.",
      "Needs high humidity — mist regularly or use a pebble tray.",
      "Use filtered water; sensitive to fluoride and salt buildup.",
      "Non-toxic to pets and children.",
    ],
  },
  {
    id: "croton",
    name: "Croton",
    emoji: "🌺",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect to direct",
    tips: [
      "Needs lots of light to maintain its bold, colorful foliage.",
      "Water when the top inch of soil is dry.",
      "Dislikes being moved — may drop leaves when relocated.",
      "Mist regularly or provide humidity to prevent leaf drop.",
      "Toxic to pets and humans; the sap can irritate skin.",
    ],
  },
  {
    id: "bird_of_paradise",
    name: "Bird of Paradise",
    emoji: "🌴",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect to full sun",
    tips: [
      "Needs at least 6 hours of bright light per day.",
      "Water deeply when the top 2 inches of soil are dry.",
      "Wipe large leaves with a damp cloth to help photosynthesis.",
      "Can bloom indoors when given enough light — takes years to mature.",
      "Toxic to pets if ingested.",
    ],
  },
  {
    id: "anthurium",
    name: "Anthurium",
    emoji: "🌸",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry; never let roots sit in water.",
      "Blooms last for weeks — the 'flower' is actually a waxy spathe.",
      "Provide high humidity for best blooming.",
      "Fertilize monthly with a phosphorus-rich fertilizer to encourage flowers.",
      "Toxic to pets and humans.",
    ],
  },
  {
    id: "begonia",
    name: "Begonia",
    emoji: "🌸",
    wateringIntervalDays: 5,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water at the base to avoid fungal issues on leaves.",
      "Allow the top inch of soil to dry between waterings.",
      "Deadhead spent blooms to encourage continuous flowering.",
      "Provide good air circulation to prevent powdery mildew.",
      "Toxic to pets — keep out of reach.",
    ],
  },
  {
    id: "african_violet",
    name: "African Violet",
    emoji: "💜",
    wateringIntervalDays: 5,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water from the bottom — wet leaves cause spots and rot.",
      "Needs consistently bright indirect light to bloom.",
      "Use African violet–specific fertilizer for best blooms.",
      "Pinch off spent flowers to encourage more blooming.",
      "Prefers slightly pot-bound conditions.",
    ],
  },
  {
    id: "christmas_cactus",
    name: "Christmas Cactus",
    emoji: "🌸",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry; reduce in winter to trigger blooming.",
      "To encourage blooming, give 12–14 hours of darkness for 6 weeks in fall.",
      "Blooms in red, pink, white, or purple near the holidays.",
      "Propagates easily from stem segments.",
      "Non-toxic to pets — a great pet-safe option!",
    ],
  },
  {
    id: "jade_plant",
    name: "Jade Plant",
    emoji: "🌿",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect to direct",
    tips: [
      "Water deeply then let soil dry out completely before watering again.",
      "Needs 4+ hours of bright light per day for the best growth.",
      "Can live for decades and develop a beautiful tree-like form.",
      "Prune to shape — cuttings root easily in soil.",
      "Toxic to pets — can cause vomiting and lethargy.",
    ],
  },
  {
    id: "haworthia",
    name: "Haworthia",
    emoji: "🌵",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the soil is completely dry — every 2–3 weeks.",
      "Tolerates lower light better than most succulents.",
      "Plant in well-draining cactus or succulent mix.",
      "Slow-growing but very long-lived.",
      "Non-toxic to pets — a great pet-safe succulent!",
    ],
  },
  {
    id: "echeveria",
    name: "Echeveria",
    emoji: "🌸",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect to full sun",
    tips: [
      "Water only when soil is completely dry — soak then let drain fully.",
      "Needs excellent drainage; never let it sit in water.",
      "The rosette shape shows stress coloring (red/purple tips) with more sun.",
      "Remove dead lower leaves to prevent pests and rot.",
      "Produces offsets ('chicks') that can be separated and repotted.",
    ],
  },
  {
    id: "rosemary",
    name: "Rosemary",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Full sun",
    tips: [
      "Prefers drier conditions — allow soil to dry between waterings.",
      "Needs at least 6–8 hours of direct sunlight per day.",
      "Great drainage is essential; use terracotta pots with drainage holes.",
      "Harvest regularly to encourage new growth and keep it bushy.",
      "Woody stems indicate mature growth — normal and healthy.",
    ],
  },
  {
    id: "thyme",
    name: "Thyme",
    emoji: "🌿",
    wateringIntervalDays: 5,
    difficulty: "Easy",
    light: "Full sun",
    tips: [
      "Let soil dry slightly between waterings — doesn't like wet feet.",
      "Thrives in full sun; 6+ hours per day indoors or outdoors.",
      "Harvest before flowering for the best flavor.",
      "Prune after flowering to encourage new leafy growth.",
      "Excellent companion plant — repels pests in the garden.",
    ],
  },
  {
    id: "mint",
    name: "Mint",
    emoji: "🌿",
    wateringIntervalDays: 3,
    difficulty: "Easy",
    light: "Bright indirect to partial sun",
    tips: [
      "Keep soil consistently moist — mint hates drying out.",
      "Pinch off flowers to keep the plant focused on leaf production.",
      "Grows aggressively — best kept in a container to prevent spreading.",
      "Harvest frequently to encourage full, bushy growth.",
      "Great for teas, cocktails, and cooking.",
    ],
  },
  {
    id: "chinese_evergreen",
    name: "Chinese Evergreen",
    emoji: "🌿",
    wateringIntervalDays: 10,
    difficulty: "Easy",
    light: "Low to medium indirect",
    tips: [
      "One of the most adaptable houseplants — tolerates low light and neglect.",
      "Water when the top inch of soil is dry.",
      "Darker leaf varieties tolerate lower light; variegated ones need more.",
      "Wipe leaves occasionally to keep them dust-free and glossy.",
      "Toxic to pets — keep out of reach.",
    ],
  },
  {
    id: "dieffenbachia",
    name: "Dieffenbachia",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Medium to bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Tolerates lower light but grows best in medium indirect light.",
      "Also called 'Dumb Cane' — sap causes temporary loss of speech if ingested.",
      "Toxic to pets and humans; wear gloves when pruning.",
      "Wipe leaves to keep them glossy and dust-free.",
    ],
  },
  {
    id: "parlor_palm",
    name: "Parlor Palm",
    emoji: "🌴",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Low to medium indirect",
    tips: [
      "One of the best palms for low-light interiors.",
      "Water when the top inch of soil is dry; avoid overwatering.",
      "Mist occasionally to increase humidity and deter spider mites.",
      "Slow-growing but can eventually reach 6 feet tall indoors.",
      "Non-toxic to pets and children.",
    ],
  },
  {
    id: "string_of_pearls",
    name: "String of Pearls",
    emoji: "🌿",
    wateringIntervalDays: 14,
    difficulty: "Moderate",
    light: "Bright indirect to direct",
    tips: [
      "Water sparingly — the pearls store water and rot easily.",
      "Needs very well-draining soil; plant in cactus mix.",
      "Best in a hanging pot where the trailing strands can cascade freely.",
      "Flat or shriveled pearls mean it needs water; mushy ones mean overwatering.",
      "Toxic to pets and humans.",
    ],
  },
  {
    id: "string_of_hearts",
    name: "String of Hearts",
    emoji: "🌿",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water only when soil is completely dry — very drought tolerant.",
      "Needs bright indirect light for the best heart-shaped leaf markings.",
      "The tubers along the vines can be propagated by laying them on moist soil.",
      "Beautiful in a hanging basket — grows long trailing vines.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "hoya",
    name: "Hoya (Wax Plant)",
    emoji: "🌿",
    wateringIntervalDays: 10,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Allow soil to dry partially between waterings.",
      "Produces clusters of star-shaped, fragrant flowers when happy.",
      "Never cut the flower spurs — new blooms appear on the same stalks.",
      "Prefers to be slightly root-bound before it will bloom.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "english_ivy",
    name: "English Ivy",
    emoji: "🌿",
    wateringIntervalDays: 5,
    difficulty: "Easy",
    light: "Bright indirect to medium",
    tips: [
      "Water when the top inch of soil is dry.",
      "Prefers cooler temperatures (50–70°F) — struggles in hot, dry rooms.",
      "Mist regularly to increase humidity and deter spider mites.",
      "Prune often to keep it full and bushy.",
      "Toxic to pets and children.",
    ],
  },
  {
    id: "lucky_bamboo",
    name: "Lucky Bamboo",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Low to medium indirect",
    tips: [
      "Can be grown in water or soil — change the water every 1–2 weeks if in water.",
      "Use filtered or bottled water; sensitive to fluoride and chlorine.",
      "Avoid direct sunlight which will scorch the leaves.",
      "Yellow leaves indicate too much sun or fluoride in the water.",
      "Considered a symbol of good luck in many cultures.",
    ],
  },
  {
    id: "yucca",
    name: "Yucca",
    emoji: "🌵",
    wateringIntervalDays: 14,
    difficulty: "Easy",
    light: "Bright indirect to full sun",
    tips: [
      "Very drought-tolerant — water deeply then allow to dry completely.",
      "Needs plenty of bright light; a south-facing window is ideal.",
      "Sharp leaf tips can be dangerous — keep away from children.",
      "Prefers terracotta pots with drainage for best airflow.",
      "Toxic to pets if ingested.",
    ],
  },
  {
    id: "ponytail_palm",
    name: "Ponytail Palm",
    emoji: "🌴",
    wateringIntervalDays: 21,
    difficulty: "Easy",
    light: "Bright indirect to full sun",
    tips: [
      "Stores water in its swollen base — extremely drought tolerant.",
      "Water very sparingly; overwatering is the main cause of death.",
      "Needs bright light; a sunny windowsill is perfect.",
      "Not actually a palm — it's related to agave plants.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "schefflera",
    name: "Schefflera (Umbrella Plant)",
    emoji: "🌳",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Needs bright indirect light — low light causes leggy growth.",
      "Mist leaves occasionally to deter spider mites.",
      "Prune to maintain shape and encourage bushier growth.",
      "Toxic to pets and humans.",
    ],
  },
  {
    id: "bromeliad",
    name: "Bromeliad",
    emoji: "🌺",
    wateringIntervalDays: 7,
    difficulty: "Moderate",
    light: "Bright indirect",
    tips: [
      "Water into the central cup (tank) formed by the leaves.",
      "Flush the cup monthly to prevent stagnant water and bacteria.",
      "Keep the soil lightly moist but not soggy.",
      "After flowering, the mother plant dies but produces pups (offsets).",
      "Needs good air circulation; avoid stagnant, humid conditions.",
    ],
  },
  {
    id: "air_plant",
    name: "Air Plant (Tillandsia)",
    emoji: "🌿",
    wateringIntervalDays: 7,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Soak in water for 20–30 minutes once a week, then shake off excess water.",
      "Always allow to dry fully within 4 hours to prevent rot.",
      "Requires no soil — can be mounted on wood or displayed in a container.",
      "Needs good air circulation; avoid enclosed terrariums.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "oxalis",
    name: "Oxalis (Wood Sorrel)",
    emoji: "💜",
    wateringIntervalDays: 5,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "Leaves and flowers fold up at night or in low light — totally normal.",
      "Goes dormant in summer; reduce watering and let it rest.",
      "Produces cheerful small flowers in pink, white, or yellow.",
      "Mildly toxic to pets in large quantities.",
    ],
  },
  {
    id: "nerve_plant",
    name: "Nerve Plant (Fittonia)",
    emoji: "🌿",
    wateringIntervalDays: 4,
    difficulty: "Moderate",
    light: "Low to medium indirect",
    tips: [
      "Keep soil consistently moist — wilts dramatically when dry (but recovers fast).",
      "Needs high humidity; thrives in terrariums.",
      "Avoid direct sunlight which bleaches the intricate leaf patterns.",
      "One of the few plants that does well in low-light bathrooms.",
      "Non-toxic to pets.",
    ],
  },
  {
    id: "wandering_dude",
    name: "Wandering Dude",
    emoji: "💜",
    wateringIntervalDays: 5,
    difficulty: "Easy",
    light: "Bright indirect",
    tips: [
      "Water when the top inch of soil is dry.",
      "More light = more vibrant purple and silver striping.",
      "Pinch back stems regularly to prevent legginess.",
      "Propagates easily in water from cuttings.",
      "Mildly irritating to some pets — monitor if chewed.",
    ],
  },
];

export const getDifficultyColor = (difficulty) => {
  switch (difficulty) {
    case "Easy": return "#4caf50";
    case "Moderate": return "#ff9800";
    case "Hard": return "#f44336";
    default: return "#9e9e9e";
  }
};

export const getWateringStatus = (lastWatered, intervalDays) => {
  if (!lastWatered) return { status: "unknown", daysUntil: null, label: "Never watered", color: "#9e9e9e" };

  const last = new Date(lastWatered);
  const now = new Date();
  const nextWatering = new Date(last);
  nextWatering.setDate(nextWatering.getDate() + intervalDays);

  const diffMs = nextWatering - now;
  const daysUntil = Math.ceil(diffMs / (1000 * 60 * 60 * 24));

  if (daysUntil < 0) {
    return { status: "overdue", daysUntil, label: `${Math.abs(daysUntil)}d overdue`, color: "#f44336" };
  } else if (daysUntil === 0) {
    return { status: "today", daysUntil, label: "Water today!", color: "#ff9800" };
  } else if (daysUntil <= 2) {
    return { status: "soon", daysUntil, label: `In ${daysUntil}d`, color: "#ff9800" };
  } else {
    return { status: "ok", daysUntil, label: `In ${daysUntil}d`, color: "#4caf50" };
  }
};
